# Generated by Django 2.1.2 on 2018-10-18 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Group name')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='A group contains many user.')),
            ],
        ),
    ]
