# Generated by Django 2.2.3 on 2019-11-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'A state'), ('B', 'B state')], max_length=2, verbose_name='state')),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
